In [2]:
import torch

In [53]:
def loadTensors(filename, out="features_out/"):
    main = torch.load("features/" + filename)
    last = torch.load("features_last/" + filename)
    print(main.shape)
    print(main[-1])
    main = main[:-1].reshape(-1, main.shape[-1])
    print(main.shape)
    print(last.shape)
    main = torch.cat((main, last), 0)
    torch.save(main, out + filename)
    print(filename + "-" + str(main.shape[0]))

In [56]:
3933*32+11

125867

In [54]:
loadTensors("s1-feat-train-bigearthnet-v1-base.pth")
loadTensors("s1-feat-test-bigearthnet-v1-base.pth")
loadTensors("s1-feat-val-bigearthnet-v1-base.pth")

torch.Size([8428, 32, 768])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
torch.Size([269664, 768])
torch.Size([31, 768])
s1-feat-train-bigearthnet-v1-base.pth-269695
torch.Size([3934, 32, 768])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
torch.Size([125856, 768])
torch.Size([10, 768])
s1-feat-test-bigearthnet-v1-base.pth-125866
torch.Size([3934, 32, 768])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0

In [50]:
loadTensors("s1-feat-train-bigearthnet-v1-large.pth")
loadTensors("s1-feat-test-bigearthnet-v1-large.pth")
loadTensors("s1-feat-val-bigearthnet-v1-large.pth")

FileNotFoundError: [Errno 2] No such file or directory: 'features_last/s1-feat-train-bigearthnet-v1-large.pth'